version: "3"

services:
  nginx:
    build: ./docker/nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/src
    networks:
      - server-net
    depends_on:
      - web
      - api
      - admin

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=web
    expose:
      - 9000
    volumes:
      # Can be disabled for production (code is baked in)
      - .:/usr/src
    networks:
      - server-net
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=api
    volumes:
      - .:/usr/src
#       - sqlite-data:/usr/data
      - ./data:/usr/data
    expose:
      - 9000
    networks:
      - server-net

  admin:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=admin
    volumes:
      - .:/usr/src
#       - sqlite-data:/usr/data
      - ./data:/usr/data
    expose:
      - 9000
    networks:
      - server-net

# If desired, the sqlite file can be stored inside docker volumes (faster).
#  No direct access to the file is then available though, and initialization must be made programmatically.
# volumes:
#   sqlite-data:

networks:
  server-net:
    driver: bridge
