version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
      args:
        - config=${NGINX_CONF:-site.conf}
    restart: unless-stopped
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
      - SSL_PORT=${HTTPS_PORT:-443}
    expose:
      - 8000
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./docker/nginx/${NGINX_CONF:-site.conf}:/etc/nginx/templates/default.conf
      - ./docker/nginx/snippets:/etc/nginx/snippets
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/certbot:/var/www/certbot
      - .:/usr/src
    networks:
      - server-net
    depends_on:
      - web
      - api
      - admin

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=web
    expose:
      - 9000
    volumes:
      # Can be disabled for production (code is baked in)
      - .:/usr/src
    networks:
      - server-net
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=api
    volumes:
      - .:/usr/src
      # If using SQLite, include volume to database file
      #- ./data:/usr/data
    expose:
      - 9000
    depends_on:
      - db
    networks:
      - server-net

  admin:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - dir=admin
    volumes:
      - .:/usr/src
      # If using SQLite, include volume to database file
      #- ./data:/usr/data
    expose:
      - 9000
    depends_on:
      - db
    networks:
      - server-net

  db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${PDO_DATABASE}
      MYSQL_USER: ${PDO_USER}
      MYSQL_PASSWORD: ${PDO_PASS}
    volumes:
      - ./data/mysql:/var/lib/mysql
    # Switch to internal data storage
    # - mysql-data:/var/lib/mysql
    networks:
      - server-net

  # Database administration tool
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8180:8080
    networks:
      - server-net

# Image for generating Let's Encrypt certificates
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./docker/nginx/ssl/certbot:/etc/letsencrypt
#      - ./docker/certbot:/var/www/certbot

# If desired, the database files can be stored inside docker volumes (faster).
#  No direct access to the files is then available though.
# volumes:
#   mysql-data:

networks:
  server-net:
    driver: bridge
